[options]
db_host = odoo-db-azure.postgres.database.azure.com
db_port = 5432
db_user = odoo17
db_password = QxAdxgCFqHshmjpqscDdwORipdGVLcqTz!
db_maxconn = 20
db_sslmode = require
proxy_mode = True
workers = 2
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
log_level = warn
list_db = False
admin_passwd = OdooMaster@2026!
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_name = ESMSOS
dbfilter = ^ESMSOS$