[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
limit_time_cpu = 600
limit_time_real = 1200
db_host = crossover.proxy.rlwy.net
db_port = 10320
db_user = odoo17
db_password = QxAdxgCFqHshmjpqscDdwORipdGVLcqT
db_name = Odoo17
db_maxconn = 5
db_sslmode = disable
admin_passwd = OdooMaster@2026!
proxy_mode = True
workers = 2
max_cron_threads = 1