http:
  routers:
    odoo-router:
      rule: "Host(`odoo.esmoshealth.me`)"
      entryPoints:
        - websecure
      service: odoo-loadbalancer
      tls:
        certResolver: letsencrypt
    moodle-router:
      rule: "Host(`moodle.esmoshealth.me`)"
      entryPoints:
        - websecure
      service: moodle-loadbalancer
      tls:
        certResolver: letsencrypt
    traefik-dashboard:
      rule: "Host(`traefik.esmoshealth.me`)"
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt

  services:
    odoo-loadbalancer:
      loadBalancer:
        sticky:
          cookie:
            name: odoo_sticky
            secure: true
        servers:
          - url: "http://10.0.1.5:8069"
          - url: "http://10.2.1.4:8069"
        healthCheck:
          path: /web/health
          interval: 10s
          timeout: 3s
    moodle-loadbalancer:
      loadBalancer:
        sticky:
          cookie:
            name: moodle_sticky
            secure: true
        servers:
          - url: "http://10.0.1.5:8080"
          - url: "http://10.2.1.4:8080"
        healthCheck:
          path: /login/index.php
          interval: 10s
          timeout: 3s
          followRedirects: false